[package]
name = "turbofibonacci"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rustler = {version="0.37.0" , features = ["big_integer"]}
num-bigint = "0.4"
num-traits = "0.2.19"
